import { AppShell } from "@/components/layout/AppShell";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Icon } from "@/components/ui/Icon";
import { Input } from "@/components/ui/Input";
import { MemberAvatar } from "@/components/trips/MemberAvatar";

const friends = [{ name: "Rahul Kapoor", username: "@rahul.k", initials: "RK", detail: "Online · Last trip: Goa", tone: "coral" as const }, { name: "Priya Shah", username: "@priyashah", initials: "PS", detail: "Planning a weekend escape", tone: "blue" as const }, { name: "Aarav Mehta", username: "@aaravm", initials: "AM", detail: "Online · Loves hidden gems", tone: "sand" as const }, { name: "Maya Iyer", username: "@maya.iyer", initials: "MI", detail: "Last trip: Coorg", tone: "pine" as const }];

export default function FriendsPage() {
  return <AppShell><div className="mx-auto max-w-5xl"><div><p className="eyebrow text-xs font-bold text-coral">Your travel circle</p><h1 className="mt-3 font-display text-4xl tracking-[-0.04em] sm:text-5xl">Go further, together.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted">Find your people, share a place, and make the plan feel collective from the start.</p></div><div className="mt-8 max-w-xl"><Input label="Find friends" placeholder="Search by name or username" /></div><div className="mt-10 grid gap-4 sm:grid-cols-2">{friends.map((friend) => <Card key={friend.username} padding="md" className="flex items-center gap-4"><MemberAvatar initials={friend.initials} tone={friend.tone} size="lg" /><div className="min-w-0 flex-1"><p className="font-display text-xl tracking-[-0.02em] text-ink">{friend.name}</p><p className="mt-1 text-xs font-semibold text-pine">{friend.username}</p><p className="mt-1.5 text-xs text-muted">{friend.detail}</p></div><Button variant="soft" className="min-h-9 px-3 text-xs"><Icon name="user-plus" size={14} /> Invite</Button></Card>)}</div><div className="mt-10 rounded-2xl border border-dashed border-muted/35 bg-paper p-8 text-center"><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-moss text-pine"><Icon name="users" size={22} /></span><h2 className="mt-4 font-display text-2xl">Friend requests will live here.</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted">Realtime updates will power friend requests, presence, and shared trip invites in the next phase.</p></div></div></AppShell>;
}
