import { AppShell } from "@/components/layout/AppShell";
import { SignOutButton } from "@/components/auth/SignOutButton";
import { Card } from "@/components/ui/Card";
import { Icon } from "@/components/ui/Icon";

const settingsSections = [
  { title: "Account", items: [{ label: "Edit profile", copy: "Name, username, photo, and bio", icon: "edit" as const }, { label: "Change password", copy: "Keep your travel space secure", icon: "lock" as const }, { label: "Email settings", copy: "Manage your account email", icon: "mail" as const }] },
  { title: "Privacy", items: [{ label: "Profile visibility", copy: "Choose who can see your profile", icon: "users" as const }, { label: "Friend requests", copy: "Control who can invite you", icon: "user-plus" as const }, { label: "Location sharing", copy: "Manage location preferences", icon: "map-pin" as const }] },
  { title: "Notifications", items: [{ label: "Trip notifications", copy: "Changes, invites, and reminders", icon: "calendar" as const }, { label: "Friend requests", copy: "New people in your circle", icon: "users" as const }, { label: "AI updates", copy: "Itinerary suggestions and weather", icon: "sparkle" as const }] },
];

export default function SettingsPage() {
  return <AppShell><div className="mx-auto max-w-4xl"><div><p className="eyebrow text-xs font-bold text-coral">Your space</p><h1 className="mt-3 font-display text-4xl tracking-[-0.04em] sm:text-5xl">Settings</h1><p className="mt-3 text-sm leading-6 text-muted">The quiet details that make Vistara feel like yours.</p></div><div className="mt-9 space-y-5">{settingsSections.map((section) => <Card padding="none" key={section.title}><div className="border-b border-line px-5 py-4 sm:px-6"><p className="eyebrow text-[10px] font-bold text-muted">{section.title}</p></div><div className="divide-y divide-line">{section.items.map((item) => <button type="button" key={item.label} className="flex w-full items-center gap-4 px-5 py-4 text-left transition hover:bg-moss/25 sm:px-6"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-moss text-pine"><Icon name={item.icon} size={17} /></span><span className="min-w-0 flex-1"><span className="block text-sm font-bold text-ink">{item.label}</span><span className="mt-1 block text-xs leading-5 text-muted">{item.copy}</span></span><Icon name="chevron-right" size={17} className="text-muted" /></button>)}</div></Card>)}<Card padding="lg"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="eyebrow text-[10px] font-bold text-muted">Appearance</p><h2 className="mt-2 font-display text-2xl">A softer interface</h2><p className="mt-2 text-sm leading-6 text-muted">Theme preferences will be available once the core travel flows are in place.</p></div><span className="rounded-full bg-moss px-3 py-1.5 text-xs font-bold text-pine">Light · Current</span></div></Card><div className="flex justify-end"><SignOutButton /></div></div></div></AppShell>;
}
